version: '3.9'

services:
  mariadb:
    image: santhoshmern/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Univers@l@123
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: santhosh
      MYSQL_PASSWORD: Univers@l@123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  laravel-api:
    image: santhoshmern/laraval-api
    container_name: laravel-api
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: santhosh
      DB_PASSWORD: Univers@l@123
    ports:
      - "8080:80"
    volumes:
      - ./laravel-api:/var/www/html

  react-app:
    image: santhoshmern/react-app:latest
    container_name: react-app
    depends_on:
      - laravel-api
    restart: unless-stopped
    ports:
      - “8081:80"
    # If needed to serve React built assets with Nginx
    # use volumes only if you want live development mapping
    volumes:
       - ./login-app/dist:/var/www/html

volumes:
  mariadb_data:
